### ISSUE TITLE
Router crashes when clients connect to nonexistent realm

### ISSUE THREAD

**Issue by Boscop** [dyule/wamp-rs#2]
When I start the router, then the endpoint, the router crashes with:
```
thread '<unnamed>' panicked at 'no entry found for key', src\libcore\option.rs:7
85
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose bac
ktrace.
stack backtrace:
   0: core::option::expect_failed
             at C:\projects\rust\src\libcore\option.rs:785
   1: core::option::Option<&alloc::arc::Arc<std::sync::mutex::Mutex<wamp::router
::Realm>>>::expect<&alloc::arc::Arc<std::sync::mutex::Mutex<wamp::router::Realm>
>>
             at C:\projects\rust\src\libcore\option.rs:293
   2: std::collections::hash::map::{{impl}}::index<collections::string::String,c
ollections::string::String,alloc::arc::Arc<std::sync::mutex::Mutex<wamp::router:
:Realm>>,std::collections::hash::map::RandomState>
             at C:\projects\rust\src\libstd\collections\hash\map.rs:1341
   3: wamp::router::ConnectionHandler::set_realm
             at ./src\router\handshake.rs:59
   4: wamp::router::ConnectionHandler::handle_hello
             at ./src\router\handshake.rs:18
   5: wamp::router::ConnectionHandler::handle_message
             at ./src\router\messaging.rs:52
   6: wamp::router::messaging::{{impl}}::on_message
             at ./src\router\messaging.rs:207
   7: ws::connection::Connection<wamp::router::ConnectionHandler>::read_frames<w
amp::router::ConnectionHandler>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0
.6.0\src\connection.rs:638
   8: ws::connection::Connection<wamp::router::ConnectionHandler>::read<wamp::ro
uter::ConnectionHandler>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0
.6.0\src\connection.rs:574
   9: ws::io::Handler<closure>::handle_event<closure>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0
.6.0\src\io.rs:538
  10: ws::io::Handler<closure>::event_loop<closure>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0
.6.0\src\io.rs:375
  11: ws::io::Handler<closure>::run<closure>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0
.6.0\src\io.rs:342
  12: ws::WebSocket<closure>::run<closure>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0
.6.0\src\lib.rs:308
  13: ws::WebSocket<closure>::listen<closure,&str>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0
.6.0\src\lib.rs:289
  14: ws::listen<&str,closure,wamp::router::ConnectionHandler>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\ws-0
.6.0\src\lib.rs:79
  15: wamp::router::{{impl}}::listen::{{closure}}
             at ./src\router\mod.rs:97
  16: std::panic::{{impl}}::call_once<(),closure>
             at C:\projects\rust\src\libstd\panic.rs:296
  17: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
             at C:\projects\rust\src\libstd\panicking.rs:454
  18: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  19: std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
             at C:\projects\rust\src\libstd\panicking.rs:433
  20: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
             at C:\projects\rust\src\libstd\panic.rs:361
  21: std::thread::{{impl}}::spawn::{{closure}}<closure,()>
             at C:\projects\rust\src\libstd\thread\mod.rs:360
  22: alloc::boxed::{{impl}}::call_box<(),closure>
             at C:\projects\rust\src\liballoc\boxed.rs:638
  23: std::sys::imp::thread::{{impl}}::new::thread_start
             at C:\projects\rust\src\libstd\sys\windows\thread.rs:50
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', sr
c\libcore\result.rs:860
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose bac
ktrace.
stack backtrace:
   0: core::result::Result<(), alloc::boxed::Box<Any>>::unwrap<(),alloc::boxed::
Box<Any>>
             at C:\projects\rust\src\libcore\result.rs:737
   1: router::main
             at ./examples\router.rs:14
error: process didn't exit successfully: `target\debug\examples\router.exe` (exi
t code: 101)
```

When I start api_user instead of endpoint, the router also crashes.

**Comment by Boscop** [comment]
Ah, it seems it's caused by the router using "kitchen_realm" but endpoint using "realm1".
When I change router.rs and pubsubclient.rs to also use "realm1", all examples work.
But, the router should not crash if a client tries to connect to a nonexistent realm, this is a huge vulnerabililty: Anyone can just connect with the wrong realm to crash the server!
This line causes the crash:
https://github.com/dyule/wamp-rs/blob/master/src/router/handshake.rs#L59
Instead of `[&realm]` it should probably use .get(&realm) and return an `Err` if that is None.
It's called from here:
https://github.com/dyule/wamp-rs/blob/master/src/router/handshake.rs#L18

**Comment by dyule** [comment]
Indeed this is a pretty big issue and is a side effect of me creating this specifically for use with another library.  I'll look into making this behaviour more reasonable in the near future.
